### ISSUE TITLE
Timers and speeds need to be tested and updated

### ISSUE THREAD

**Issue by olandra** [olandra/CBSafe-Simulation#30]
- [x] Update all states to fetch the speed from the list
- [x] Update the speed list to have values for all tasks

---

## Testing task

**See the comment for the information picked from the manuscript**

The speed values are set in ScenarioVariables.Start()
Currently starting from line 326

- [ ] Adjust the speeds to match reality

The timers can be found in the ScenarioVariables.Start()
Currently starting from line 259

- [ ] Set ScenarioVariables.DevMode to false to use the values in the ScenarioVariables - Currently at line 255
- [ ] Adjust the timers to match reality

**Comment by olandra** [comment]
# Simulation leader choices

## Case 1

### Task 1: Intelligence gathering

#### RPAS

- Not on bad weather
- Live feed in 2 mins
- Option to use thermal camera

#### ROV

- Not on bad weather
- Live feed in 5 mins
- 2 mins later finds person underwater at the bottom

### Task 2: Rescue

#### Waterdiving: From boat

- Sector search: 12 mins
- Perimeter exploration: 12 mins
- Direct navigation: 10 mins

#### Waterdiving: From shore

- Sector search: 6 mins
- Perimeter exploration: 8 mins
- Direct navigation: 4 mins

#### Surface rescue by pairs

- Both swim
- First rescue: 3 mins
- Second rescue: 5 mins

#### Rescue by boat

- Boat is led into the water and goes to pick up the victims
- Victims picked up in 15 mins

#### Rescue from a burning boat

- Picked up by the fire brigade's boat or to the shore with compressed air devices

### Task 3: Fire extinguishing

#### From the beach using foam

1. Foam inventory is done
2. Foam is fired onto the ship from the beach
3. Fire is extinguished in 14 mins

#### From a ship using foam

1. A hose is led to the fire brigade's boat
2. Boat drives next to the burning boat
3. Foam sprayed onto the burning motor
4. Fire is extinguished in 10 mins

Foam inventory done?

#### Initial extinguishing using equipment on the burning boat

1. Extinguishers with compressed air devices go into the burning ship via a ladder
2. Extinguish the fire with 4 fire extinguishers
3. Fire is extinguished in 5 mins

#### From the shore or ship with water

- Fire keeps burning
- Boat starts sinking in 5 mins

### Task 4: Damage control

- Ship beaming with a boundary boom: Slow cropping of the leakage, leakage stays local. 
- Ship beaming with a suction boom: Fast cropping of the leakage, leakage stays local. 
- Canal beaming with a suction boom: Fast cropping of the leakage, but leakage has spread to a large area. 
- Canal beaming with a boundary boom: Slow cropping of the leakage, but leakage has spread to a large area.
